### ISSUE TITLE
Tuning config for large-scale point clouds

### ISSUE THREAD

**Issue by Ritchizh** [hustvl/HAIS#15]
Hi!
I am testing HAIS performance on my custom data. For small point clouds it works OK, but for large ones (20 million points) it throws out an error:
```
RuntimeError: /HAIS/lib/spconv/src/spconv/spconv_ops.cc 40
batchSize * outputVolume < std::numeric_limits::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits::max() = 2e9
```
I guess I should reduce the batch size and other parameters accordingly.
**Could you please tell what are scale, full_scale, max_npoint parameters in the config file?**
```
  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50 -> voxel_size 0.02m
  batch_size: 4
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean
```
As far as I can see, full_scale is used in clusters_voxelization() – why is it [128, 512]?

**Comment by outsidercsy** [comment]
Please refer to Line 173 in scannetv2_inst.py. If the number of point exceeds 'max_npoint', the scene will be cropped gradually until the number of remaining points is smaller than 'max_npoint'. It's to avoid out of memory. The second value of 'full_scale' 512 is the initial spatial shape of the scene before cropping. 
The first value of 'full_scale' 128 is the minimum of spatial shape. See Line 263 in scannetv2_inst.py. 
Hope these can help you.

**Comment by outsidercsy** [comment]
Please refer to Line 173 in scannetv2_inst.py. If the number of point exceeds 'max_npoint', the scene will be cropped gradually until the number of remaining points is smaller than 'max_npoint'. It's to avoid out of memory. The second value of 'full_scale' 512 is the initial spatial shape of the scene before cropping. 
The first value of 'full_scale' 128 is the minimum of spatial shape. See Line 263 in scannetv2_inst.py. 
Hope these can help you.

**Comment by Ritchizh** [comment]
Thank you for your detailed response.
I can see now that 'scannetv2_inst.py.' inherits from PointGroup data loader. But I still have trouble with understanding underlying voxelization logic 😞

I'm running HAIS in test mode, there seems to be no cropping in testMerge(), and fixed `batch_size=1` in testLoader(): 
https://github.com/hustvl/HAIS/blob/73a6f591ad29e3399ea83e9a669873fe9bb05ab0/data/scannetv2_inst.py#L98-L99

Does this mean that a large point cloud cannot be input in test mode?

**Comment by outsidercsy** [comment]
Judged from your error log, the error comes from spconv lib. Your point cloud sceces are spatially extremely large. If the voxel size is too small, the voxelization process will generate a large amount of voxels, which exceed the limitation of spconv.

Following are two tips to reduce the voxel number.
1) Adopt a larger voxel size to reduce the number of voxels. E.g.,  scale: 500.  In this way, you should retrain the model for high performance.
2) Downsample point clouds or crop the scenes before inference.

**Comment by meidachen** [comment]
> Judged from your log, the error comes from spconv lib. Your point cloud sceces are spatially extremely large. If the voxel size is too small, the voxelization process will generate a large amount of voxels, which exceed the limitation of spconv.
> 
> Following are two tips to reduce the voxel number.
> 
> 1. Adopt a larger voxel size to reduce the number of voxels. E.g.,  scale: 500.  In this way, you should retrain the model for high performance.
> 2. Downsample point clouds or crop the scenes before inference.

Hi @outsidercsy , thanks for the great work. I just want to get clarify, would a small scale number mean large voxel size? in config: # voxel_size = 1 / scale, scale 50 -> voxel_size 0.02m. And E.g., scale: 500 actually means 0.002m model size?

**Comment by meidachen** [comment]
Hi @Ritchizh, could you please share the config that works for you if possible? Thank you!

**Comment by outsidercsy** [comment]
Yes, you are right.

**Comment by meidachen** [comment]
> Yes, you are right.

Thank you for your reply. I have a follow-up question and hope you could help me with it if possible. I'm having a hard time understanding the "score_fullscale" in the config. I saw it in the clusters_voxelization for computing the scale of each cluster and at the end, it checks (clusters_coords >= 0) * (clusters_coords < full-scale).
 
I'm confused with it. Does this score_fullscale relate to the total size of an entire voxel?

The data I'm working with is an outdoor scene with instances of objects of very different sizes like cars, light poles, and buildings. So a cluster could be a car of 4meter * 5meter*3 meter, or a building of 10 meters by 15 meters by 20 meters. The point cloud is already downsampled with a point spacing of 0.3 meters. And I'm using a scale: 3, score_scale: 3. How should I define this score_fullscale? Do you have any recommendations?

Thank you in advance for your help!

**Comment by Ritchizh** [comment]
Thanks for all replies, I have switched to smaller point clouds, so am closing this issue for now.
