### ISSUE TITLE
S3DIS usage

### ISSUE THREAD

**Issue by GooseFather990** [hustvl/HAIS#22]
Hello,
I see that your code looks simular to SoftGroup (they probably copied from you, but let's put that aside).
I want to test HAIS on the S3DIS dataset but I see no readme file that shows me how to do so. I could try to modify it myself but I see that you also have benchmark results on S3DIS so it would be nice to get the files to make it work (and how).
Finally I am curious about the visualisation for S3DIS, do you have something for this as well?
I look forward to hearing from you!
Kind Regards,
Goose.

**Comment by CodeFly-123** [comment]
hi.Have you solved it now?

**Comment by GooseFather990** [comment]
> hi.Have you solved it now?

@CodeFly-123 No I have not fixed HAIS. I am using SoftGroup now, works fine besides a small memory leak but I am not sure it is on my side of in the code.

**Comment by CodeFly-123** [comment]
@GooseFather990  I also am using SoftGroup now, But test large scene on s3dis dataset，
The result was a little bad. for example Area_2_auditorium_2_inst_nostuff.pth file. Can you test it and see how it works well？Thank you very much if you can.

**Comment by GooseFather990** [comment]
@CodeFly-123 I saw some decent results for instance segmentation. I got an average of 66%AP on Area_5 with loss still going down (view with tensorboard). Now I am using a custom dataset so you cannot compare these numbers anymore with a custom situation. If u use it in semantic only however, the results are great. With some external magic you can make the grouping more efficient compared to the instance segmentation but ohw well...

**Comment by CodeFly-123** [comment]
@GooseFather990  Thank you！ I also got an average of 66%AP on Area_5. but when test alone "Area_2_auditorium_2_inst_nostuff.pth" scene in Area_2, the result was a little bad. If it's convenient for you, you can test it and visualize it. We can compare and verify the results. Because Area_2 is used as train set，I think Its result won't be too bad. I doubt that the ability to big scenes is still limited. I've been trying to solve this problem recently.
I hope we can communicate and solve problems together.

**Comment by Greatest-Marx** [comment]
> 我在实例细分方面看到了一些不错的结果。我在Area_66上的平均AP为5%，损失仍在下降（使用张量板查看）。现在我使用的是自定义数据集，因此您无法再将这些数字与自定义情况进行比较。但是，如果您仅在语义中使用它，则结果很棒。与实例分段相比，使用一些外部魔法，您可以使分组更有效，但是哦，好吧......

Hello! I am currently replicating the experiment on SoftGroup, but my computer only has one GPU. When I change the command line from "./tools/dist_train. sh configs/softgroup_stpls3d_backup. yaml 4" to "./tools/dist_train. sh configs/softgroup_stpls3d_backup. yaml 1", I can read the parameters in the. yaml file normally, but I still report an error: "RuntimeError: CUDA error: invalid device function". Do you know why this is
