### ISSUE TITLE
gcc-5 Install error

### ISSUE THREAD

**Issue by sobikim** [hustvl/HAIS#24]
Hi. Thank you for great work.
I'm using colab to run HAIS.(I installed condacolab in  colab)

When I run this command,
conda install -c daleydeng gcc-5

I got the this error.

The following NEW packages will be INSTALLED:

  gcc-5              daleydeng/linux-64::gcc-5-5.4.0-2
  gmp                conda-forge/linux-64::gmp-6.2.1-h58526e2_0
  isl                daleydeng/linux-64::isl-0.17.1-0
  mpc                conda-forge/linux-64::mpc-1.2.1-h9f54685_0
  mpfr               conda-forge/linux-64::mpfr-4.1.0-h9202a9a_1

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            anaconda::certifi-2021.10.8-py37h06a4~ --> conda-forge::certifi-2021.10.8-py37h89c1867_2
  conda               anaconda::conda-4.12.0-py37h06a4308_0 --> conda-forge::conda-4.12.0-py37h89c1867_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(732): An error occurred while installing package 'daleydeng::gcc-5-5.4.0-2'.
Rolling back transaction: done

LinkError: post-link script failed for package daleydeng::gcc-5-5.4.0-2
location of failed script: /usr/local/bin/.gcc-5-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Installation failed: gcc is not able to compile a simple 'Hello, World' program.

stderr: ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crt1.o': File exists
ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crti.o': File exists
ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crtn.o': File exists
/usr/local/bin/../gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
return code: 1

How can I solve this?
Any help would be appreciated.

**Comment by YellowPuppy** [comment]
> Hi. Thank you for great work. I'm using colab to run HAIS.(I installed condacolab in colab)
> 
> When I run this command, conda install -c daleydeng gcc-5
> 
> I got the this error.
> 
> The following NEW packages will be INSTALLED:
> 
> gcc-5 daleydeng/linux-64::gcc-5-5.4.0-2 gmp conda-forge/linux-64::gmp-6.2.1-h58526e2_0 isl daleydeng/linux-64::isl-0.17.1-0 mpc conda-forge/linux-64::mpc-1.2.1-h9f54685_0 mpfr conda-forge/linux-64::mpfr-4.1.0-h9202a9a_1
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
> certifi anaconda::certifi-2021.10.8-py37h06a4~ --> conda-forge::certifi-2021.10.8-py37h89c1867_2 conda anaconda::conda-4.12.0-py37h06a4308_0 --> conda-forge::conda-4.12.0-py37h89c1867_0
> 
> Preparing transaction: done Verifying transaction: done Executing transaction: done ERROR conda.core.link:_execute(732): An error occurred while installing package 'daleydeng::gcc-5-5.4.0-2'. Rolling back transaction: done
> 
> LinkError: post-link script failed for package daleydeng::gcc-5-5.4.0-2 location of failed script: /usr/local/bin/.gcc-5-post-link.sh ==> script messages <== ==> script output <== stdout: Installation failed: gcc is not able to compile a simple 'Hello, World' program.
> 
> stderr: ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crt1.o': File exists ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crti.o': File exists ln: failed to create symbolic link '/usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/crtn.o': File exists /usr/local/bin/../gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory return code: 1
> 
> How can I solve this? Any help would be appreciated.

hello, how do you fix the bug?
