### ISSUE TITLE
sumNPoint meaning

### ISSUE THREAD

**Issue by sobikim** [hustvl/HAIS#26]
Thank you for the great work.

What is the meaning of "sumNPoint" ?
(# proposals_idx: (sumNPoint, 2), int, cpu)
Thank you.

**Comment by outsidercsy** [comment]
'sumNPoint' means the number of point  of all proposals.  E.g., there are three proposals, respectively with 10,   50,  100 points. Then sumNPoint is 160.

**Comment by sobikim** [comment]
Thank you very much!
