### ISSUE TITLE
config parameters meaning

### ISSUE THREAD

**Issue by Ritchizh** [hustvl/HAIS#28]
Hi!
Could you please clarify the meaning of the following parameters in config:

1)   **point_aggr_radius**: 0.03 -- this must be r_point bandwidth mentioned in the Paper. How does it work? Is it correct that:
For every pair of voxels, 2cm in size, having same semantic label, if their spatial distance is smaller than 3 cm, they are united into one set?
2) What is **cluster_shift_meanActive** ?
3) Why is **score_scale** different from data **scale**? What are score_scale: 50 and **score_fullscale**: 20?
4) In hierarchical_aggregation, class_numpoint_mean_dict and class_radius_mean - do you intentionally set [-1] value for floor and wall classes to exclude them from instances prediction?

**Comment by Greatest-Marx** [comment]
Hello, have you figured out cluster_shift_meanActive and score_scale?
